CREATE TABLE MAIL_ACCOUNT
(
	BOXID NUMBER(19) NOT NULL,
	DESCRIPTION VARCHAR2(64) NOT NULL,
	EMAILADDRESS VARCHAR2(64) NOT NULL,
	PASSWORD VARCHAR2(64) NOT NULL,
	SERVER VARCHAR2(64) NOT NULL,
	PORT NUMBER(19) NOT NULL
);

CREATE TABLE MAIL
(
	MESSAGEID NUMBER(19) NOT NULL,
	BOXID NUMBER(19) NOT NULL,
	DATE DATE NOT NULL,
	SENDER VARCHAR2(64) NOT NULL,
	SUBJECT VARCHAR2(64) NOT NULL,
	MESSAGETYPE VARCHAR2(64) NOT NULL,
	H_MESSAGEID VARCHAR2(255) NOT NULL,
	H_XRIFERIMENTOMESSAGEID VARCHAR2(255) NOT NULL,
	HASH VARCHAR2(64),
	FSPATH VARCHAR2(255) 
);